### ISSUE TITLE
Flake8 F821 Error With New Type Hints

### ISSUE THREAD

**Issue by eselimsen** [trinhanhngoc/pycharm-odoo#227]
Hi @trinhanhngoc 
I was just enjoying new type hints, but faced errors on my pre-commit hook.
Looks like Flake8 is confused by undefined name "odoo" in type hints.

Errors are gone if I `import odoo`, but would like to avoid it if possible (to keep codebase clean).

Any ideas to fix this?

![Screenshot_20221124_182135](https://user-images.githubusercontent.com/61320931/203818818-6dd0fed7-5802-410b-ab68-bc59aea87b1d.png)

![Screenshot_20221124_182116](https://user-images.githubusercontent.com/61320931/203818766-3802551f-0c8f-48f4-a129-86781dafbd07.png)

Thanks

**Comment by trinhanhngoc** [comment]
Hi @eselimsen ,

In the long run, I think it's still necessary to import to have a properly type annotation. However, if you really want to avoid these warnings from Flake8, I will develop a flake8 plugin to solve it, then you will need to install that plugin on pypi and adjust the flake8 command line argument to load it.

**Comment by eselimsen** [comment]
Hi @trinhanhngoc
Sorry for the late reply.

I go with `import odoo` for now. Flake8 plugin would be good, I could just include it with other flake8 plugins I have in pre-commit, like bugbear (I use `additional_dependencies` for packages).

But, for now I wouldn't want to take much of your time just for this, as I have an acceptable workaround for this, not the highest priority. Teaching flake8 about Odoo and this plugin would be great sometime though.
:D

**Comment by trinhanhngoc** [comment]
Hi @eselimsen , Hope you don't find it too inconvenient to import for the type annotation. Anyway, `flake8-bugbear` seems to be a good plugin. Thanks!.

**Comment by jcfernandez-890825** [comment]
Confirming this still affects Ruff (F821), the modern Flake8 replacement, as of 2026 (pycharm-odoo 1.13.23) — same root cause, `odoo` isn't a real bound name when used as a bare inline annotation.

A cleaner workaround than `import odoo`, for anyone landing here: move the type declaration into the docstring's `:type:` line instead of a real PEP 3107 annotation:

```python
def grp_fn(_carrier):
    """ :type _carrier: odoo.model.delivery_carrier """
    ...
```

Ruff/Flake8 don't parse docstring content as code, so there's nothing to flag — no dummy import needed, and PyCharm still resolves the type from the docstring form the same way it does from an inline annotation.

Is an actual fix feasible on the plugin side rather than a workaround — e.g. could the plugin itself suppress/annotate its own `odoo.model.*` sentinel so Ruff/Flake8 don't need a separate plugin to understand it, or is a dedicated linter plugin still the only realistic path?

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 ,

How are you using Ruff in PyCharm, through a built-in feature or a plugin?

**Comment by jcfernandez-890825** [comment]
Built-in — PyCharm's native Ruff integration (the `PyToolsState` component), not a separate marketplace plugin. Confirmed in this project's own `.idea/pyLspTools.xml`:
```xml
<component name="PyToolsState">
  <option name="tools">
    <map>
      <entry key="ruff">
        <value>
          <ToolEntry>
            <option name="enabled" value="true" />
          </ToolEntry>
        </value>
      </entry>
    </map>
  </option>
</component>
```
