### ISSUE TITLE
Cannot resolve format selection value reference in report.paperformat

### ISSUE THREAD

**Issue by jerzyk** [trinhanhngoc/pycharm-odoo#264]
odoo R14

while defining a new paper format in xml (model=report.paperformat, got a warning on "format" field: Cannot resolve symbol

<img width="596" alt="Screenshot 2022-12-19 at 15 08 45" src="https://user-images.githubusercontent.com/199073/208444602-3f0662b0-7a91-45eb-b282-a6fccb598b94.png">

**Comment by trinhanhngoc** [comment]
Hi @jerzyk 

Thank you for reporting. Because the selection field `format` use the list comprehension for the value definition that the Odoo plugin can not understand yet (https://github.com/odoo-ide/pycharm-odoo/issues/107).

<img width="753" alt="image" src="https://user-images.githubusercontent.com/11208291/208445817-8eb73ea9-1eea-4282-88ca-b4e2f217d8a7.png">

In the next version, the Odoo plugin will suppress warnings for such case.

**Comment by trinhanhngoc** [comment]
Hi @jerzyk ,

The new version 2022.7.4 has been released to address this issue.
