### ISSUE TITLE
Consider adding support for Odoo OCA Components

### ISSUE THREAD

**Issue by pnajman-modoolar** [trinhanhngoc/pycharm-odoo#342]
Hi @trinhanhngoc,

I'm evaluating your plugin for a while now and I absolutely love it. 
It's like ReSharper for Odoo :)

I was wondering if you'd consider adding support for Odoo OCA Components to your backlog?
Components are a highly used in Odoo world and they are something like a light weight models but not just quite.

This article explains it very nicely: https://dev.to/guewen/introduction-to-odoo-components-bn0
And here is the GitHub Repo: https://github.com/oca/connector

It's a small module but very effective and adding support for it would make Odooers very happy :)
Not to mention covering the whole connector framework, but lets not get greedy :)

Thanks much and keep up the good work,
Petar

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar , it's already in my backlog (https://github.com/odoo-ide/pycharm-odoo/issues/179). I will implement it sooner if it's widely used.

**Comment by jcfernandez-890825** [comment]
Well, know we are 3 hehe. I don't understand why this approach is not widely used. This makes models thinner, avoids namespace coalitions. Since this is composition over inheritance, it makes takes care of a lot of other things. You are deduplicating, you are doing KISS and DRY code, you are encapsulating and making easier to do tests....

Please @trinhanhngoc, we need this.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 

Since v2023.6.0.231 did some changes model class recognition. I'm now getting a lot of "Unresolved attribute reference" on my OCA components. Also, before this, I could at least get some sort of navigation for inherited methods on components.

OCA components helps a lot when you have to develop a connection between Odoo and some 3rd party API.

Please !!! Could you consider doing this ??? 
I now feel like a junkie that lost his dealer. LoL.

**Comment by trinhanhngoc** [comment]
> @trinhanhngoc
> 
> Since v2023.6.0.231 did some changes model class recognition. I'm now getting a lot of "Unresolved attribute reference" on my OCA components. Also, before this, I could at least get some sort of navigation for inherited methods on components.
> 
> OCA components helps a lot when you have to develop a connection between Odoo and some 3rd party API.
> 
> Please !!! Could you consider doing this ??? I now feel like a junkie that lost his dealer. LoL.

Hi @jcfernandez-890825. I will add support for OCA components in the next version released next week.

**Comment by jcfernandez-890825** [comment]
@trinhanhngoc 

You are the best!!!
I can't wait, you deserve nothing but good things in your life.

**Comment by pnajman-modoolar** [comment]
@trinhanhngoc Thanks dude! :)

**Comment by trinhanhngoc** [comment]
Hi @pnajman-modoolar @jcfernandez-890825 The new version 2023.6.1 has been released with initial support for OCA Components. Since the component inheritance mechanism is the same as the one for models, all features related to inheritance are supported for components as well. Special component features will be added in future releases. If you have any suggestions to improve component support, feel free to create other issues.

**Comment by jcfernandez-890825** [comment]
Thanks a lot @trinhanhngoc .
I will test this later today. Lately, I have been tasked to develop delivery method connectors as well as POS payment methods for Iceland. Using OCA component makes this easier as you can create the business logic as components, API parameters (URL, API key/token, etc) on the collection as well as factory methods for creating and using the appropriate component. The whole process becomes cleaner and easy to maintain and extend.

As the Mandalorian says ...
This is the way.
