### ISSUE TITLE
Error highlight in XML attribute values which contain %()d

### ISSUE THREAD

**Issue by lghbeta** [trinhanhngoc/pycharm-odoo#39]
1. XML warning when using format string "%()"

2. Auto Format code is wrong, a whitespace is added after "%"

![1634871266(1)](https://user-images.githubusercontent.com/3282698/138385859-6adf5f9d-7bf6-4865-b7c7-6b1c3c188a34.png)

**Comment by trinhanhngoc** [comment]
@lghbeta What are `product_attribute_tech` and `product_attribute_compo` in your screenshot?

**Comment by lghbeta** [comment]
> @lghbeta What are `product_attribute_tech` and `product_attribute_compo` in your screenshot?

This is the XMLID in my custom addons, and it also applies to the odoo standard XMLID，E.g.: %(product.product_category_1)d

**Comment by trinhanhngoc** [comment]
@lghbeta This is a limitation since it is not valid Python expression. Odoo replaces these format strings with record ids before evaluating the expression (https://github.com/odoo/odoo/blob/92588032c4f124f822b6beece9ac520a38931483/odoo/addons/base/models/ir_ui_view.py#L282). Maybe I will disable Python highlight for the xml attribute values which contain `%()d`,... in the next version.

**Comment by trinhanhngoc** [comment]
I finally found a perfect solution for this issue. There will also be code completion for XML ID in `%()d` in the next release 2021.2.10.

**Comment by lghbeta** [comment]
@trinhanhngoc Perfect! thank you very much
