### ISSUE TITLE
Support new model class style in Odoo 19

### ISSUE THREAD

**Issue by vchu-odoo** [trinhanhngoc/pycharm-odoo#502]
After [changes](https://github.com/odoo/odoo/commit/f10bd8ddcf99c9247dca417fefbc260454d74ea1) made recently in the framework. The plugin does not recognize models and their methods anymore.
![image](https://github.com/user-attachments/assets/b492f0b9-8a28-4864-b95d-ea88992a679e)

**Comment by trinhanhngoc** [comment]
Hello @vchu-odoo ,

I know that. I am working on supporting the new model class style in Odoo 19. Stay tuned.

**Comment by trinhanhngoc** [comment]
Hello @vchu-odoo 

The new version 2024.9.0 has been released with initial support for the new model class style in Odoo 19. There are still many ORM changes coming, I will update the Odoo plugin as soon as the changes are merged.

**Comment by vchu-odoo** [comment]
Thank you for the update!

**Comment by jcfernandez-890825** [comment]
Following up on the "initial support... many ORM changes coming" note from Oct 2024 — is a dedicated `odoo-stubs19` package planned, or is `odoo-stubs18` the intended fallback for Odoo 19 core-framework resolution for now?

Confirmed no `odoo-stubs19` directory ships with the current plugin (1.13.23, Aug 2026) across every install I checked (`odoo-stubs10` through `odoo-stubs18` only). Working on an Odoo-19-only project, so any answer on current v19 stub coverage — even "not yet, still in progress" — would help set expectations for what's safe to trust vs. verify manually.

**Comment by trinhanhngoc** [comment]
@jcfernandez-890825 ,

`odoo-stubs` is no longer needed for Odoo >= 19. Odoo has been adding type annotations into the source code itself.

Btw, the latest version of the Odoo IDE plugin is 2026.5.1, not 1.13.23 =))

**Comment by jcfernandez-890825** [comment]
Thanks — that answers it. Good to know the type annotations moving directly into Odoo's own source obsoletes `odoo-stubs19` outright rather than it still being in progress; simpler than what I was expecting.

You're right on the version too — I checked PyCharm's plugin settings directly this time: `dev.ngocta.pycharm-odoo (2026.5.1.262)`. The `1.13.23` I quoted earlier was wrong, it belongs to an unrelated plugin I'd been discussing in a different thread that same week. Thanks for catching it.
