### ISSUE TITLE
Ctrl+Click for variables containing Selection fields values

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#62]
![image](https://user-images.githubusercontent.com/28876647/150335716-7f60e3af-5fb0-4785-8660-8e7a7850ff11.png)

![image](https://user-images.githubusercontent.com/28876647/150335485-3676c460-5936-4777-92a7-bbcffcd34a7a.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

Due to performance issues and implementation complexity, I will take another approach which is less precise but supports more symbol types in more contexts. In the next version,  I'm going to implement **Go to Declaration**  feature for all suitable python strings in unknown contexts. Example, in your sample above, when Ctrl+Click will result in all symbols matching `send_err` including models, fields, contexts, selections, XML IDs,...

**Comment by jcfernandez-890825** [comment]
You are a genius man. Odoo should hire you, 'cause you are doing the impossible with this plugin.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 , the new version has been released.

**Comment by jcfernandez-890825** [comment]
As usually, you rock. This is by far the greatest plugin ever.
