### ISSUE TITLE
Attribute name is not allowed here.

### ISSUE THREAD

**Issue by jcfernandez-890825** [trinhanhngoc/pycharm-odoo#90]
src/odoo/odoo/addons/sale/views/sale_views.xml | View XML_ID = view_order_form
![image](https://user-images.githubusercontent.com/28876647/171712361-95c32738-c6ee-4f0d-a25e-b0669e18505e.png)

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 

The plugin uses odoo rng https://github.com/odoo/odoo/blob/5020f6eb91f2c84eaaa4ba65f5a25ae8f04820a0/odoo/addons/base/rng/common.rng#L422 for xml completion and validation. Sometimes rng data doesn't provide full available attributes and the plugin needs to do some extra work.

Thank you again. This issue will be fixed in the next version.

**Comment by trinhanhngoc** [comment]
Hi @jcfernandez-890825 The new version 2022.4 has been released with the fix for this issue.
